### ISSUE TITLE
可以实时更新这个进度吗。。

### ISSUE THREAD

**Issue by k99k5** [cao19881125/XpTimer#1]
可以实时更新这个进度吗。。

**Comment by cao19881125** [comment]
在哪里更新？github上你可以watch一下，后面更新了会自动发你邮件的

**Comment by k99k5** [comment]
我是说插件里的这个经验统计  能不能实时更新。。

**Comment by cao19881125** [comment]
现在是实时更新的啊，3秒更新一次，不过现在有个bug，如果不设置目标，更新会断掉，今晚你再pull一下就可以了，就修复了

**Comment by cao19881125** [comment]
兄弟，能不能给点个star ☺
